In [15]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


In [16]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2.shape)
print(arr2.size)

(2, 3)
6


In [ ]:
print(arr2 -1)
print(arr2 * 3)

[[0 1 2]
 [3 4 5]]
[[ 3  6  9]
 [12 15 18]]


In [ ]:
print(np.sqrt(arr2))
print(np.exp(arr2))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [ ]:
print(arr2[0, 1])

2


In [12]:

print(arr2[0:-1])
print(arr2[0,:])


[[1 2 3]]
[1 2 3]


In [ ]:
print(arr2[arr2 > 4])

[5 6]


In [ ]:
arr3=arr2.reshape(3,2)
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
arr4 = np.array([1, 2, 4])
arr5 = np.array([4, 5, 6])
concat=np.concatenate((arr4, arr5))

print(concat)

[1 2 4 4 5 6]


In [ ]:
spli=np.split(concat,3)
print(spli)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
ran=np.arange(5,15)
print(ran)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
difran=np.linspace(0,100,11)
print(difran)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [17]:
array = np.random.randint(0, 100, (4, 4))
print( array)

[[70 52 59 51]
 [71 43 15 15]
 [45 72 30 90]
 [99 72 14  9]]


In [18]:
np.save("random_array.npy", array)

In [ ]:
loaded_array = np.load("random_array.npy")  # Loads the saved array from the file
print("Loaded Array:\n", loaded_array)

Loaded Array:
 [[31 35 54 16]
 [65 64 50 58]
 [27 37 77 56]
 [47  8  9 63]]
